baseurl = "https://altran-data-analytics.netlify.com/"
title = "Data Analytics"
theme = "test"
languageCode = "en-us"
copyright = "Altran Belgium"
disqusShortname = "altran-data-analytics"
disqus_identifier = "altran-da"
disqus_title = "Altran Data Analytics"
googleAnalytics = "XXX"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
rssLimit = 20

[Author]
# name = "Data Analytics team at Altran Belgium"
# profile = "https://linkedin.com/in/florianzenoni/"

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.speakerDeck]
    disable = false
  [privacy.twitter]
    disable = false
    enableDNT = false
  [privacy.vimeo]
    disable = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Data Analytics at Altran Belgium"
    description = "Engineering, data, maps!"
    # github = "https://github.com/fzenoni"
    # gitlab = "https://gitlab.com/XXX"
    # linkedin = "https://linkedin.com/in/florianzenoni/"
    # gplus = "https://google.com/+XXX"
    # twitter = "https://twitter.com/FlorianZenoni"
    #stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    # email = "florian.zenoni@altran.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

# [[menu.main]]
#     name = "Projects"
#     url = "/project/"
#     weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3
