baseurl = "/"
title = "Data Analytics"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Florian Zenoni"
disqusShortname = "XXX"
googleAnalytics = "XXX"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Author]
name = "Florian Zenoni"
profile = "https://linkedin.com/in/florianzenoni/"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Data Analytics & Co."
    description = "Engineering, data, maps!"
    # github = "https://github.com/fzenoni"
    # gitlab = "https://gitlab.com/XXX"
    # linkedin = "https://linkedin.com/in/florianzenoni/"
    # gplus = "https://google.com/+XXX"
    # twitter = "https://twitter.com/FlorianZenoni"
    #stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    # email = "florian.zenoni@altran.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

# [[menu.main]]
#     name = "Projects"
#     url = "/project/"
#     weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3
